// Validates the Rust binding against the shared cross-language vectors in
// ../../vectors (generated by @noble/post-quantum, the FIPS reference).
use serde_json::Value;
use std::fs;

fn load(name: &str) -> Value {
    let p = format!("{}/../vectors/{}", env!("CARGO_MANIFEST_DIR"), name);
    serde_json::from_str(&fs::read_to_string(p).unwrap()).unwrap()
}
fn hb(v: &Value, k: &str) -> Vec<u8> {
    hex::decode(v[k].as_str().unwrap()).unwrap()
}

macro_rules! sig_vectors {
    ($test:ident, $file:expr, $level:path) => {
        #[test]
        fn $test() {
            use $level as s;
            for c in load($file)["cases"].as_array().unwrap() {
                assert!(
                    s::verify(&hb(c, "publicKey"), &hb(c, "message"), &hb(c, "signature")),
                    "{} vector must verify",
                    $file
                );
            }
        }
    };
}
sig_vectors!(ml_dsa_44_vectors, "ml-dsa-44.json", qorechain_pqc::mldsa::ml_dsa_44);
sig_vectors!(ml_dsa_65_vectors, "ml-dsa-65.json", qorechain_pqc::mldsa::ml_dsa_65);
sig_vectors!(ml_dsa_87_vectors, "ml-dsa-87.json", qorechain_pqc::mldsa::ml_dsa_87);

macro_rules! kem_vectors {
    ($test:ident, $file:expr, $level:path) => {
        #[test]
        fn $test() {
            use $level as s;
            for c in load($file)["cases"].as_array().unwrap() {
                let ss = s::decapsulate(&hb(c, "secretKey"), &hb(c, "cipherText")).unwrap();
                assert_eq!(ss.to_vec(), hb(c, "sharedSecret"), "{} decaps mismatch", $file);
            }
        }
    };
}
kem_vectors!(ml_kem_512_vectors, "ml-kem-512.json", qorechain_pqc::mlkem::ml_kem_512);
kem_vectors!(ml_kem_768_vectors, "ml-kem-768.json", qorechain_pqc::mlkem::ml_kem_768);
kem_vectors!(ml_kem_1024_vectors, "ml-kem-1024.json", qorechain_pqc::mlkem::ml_kem_1024);

#[test]
fn shake256_vectors() {
    for c in load("shake-256.json")["cases"].as_array().unwrap() {
        let msg = hb(c, "message");
        assert_eq!(qorechain_pqc::shake256(&msg).to_vec(), hb(c, "out32"));
        let mut out64 = [0u8; 64];
        qorechain_pqc::shake256_xof(&msg, &mut out64);
        assert_eq!(out64.to_vec(), hb(c, "out64"));
    }
}

#[test]
fn roundtrip_and_helpers() {
    let (pk, sk) = qorechain_pqc::mldsa::default::keygen().unwrap();
    let sb = qorechain_pqc::hybrid_sign_bytes(&[1, 2, 3], &[9, 9]);
    assert_eq!(sb, vec![0, 0, 0, 3, 1, 2, 3, 0, 0, 0, 2, 9, 9]);
    let sig = qorechain_pqc::mldsa::default::sign(&sk, &sb).unwrap();
    assert!(qorechain_pqc::mldsa::default::verify(&pk, &sb, &sig));
    assert_eq!(qorechain_pqc::pubkey_hash20(&pk).len(), 20);

    let (ek, dk) = qorechain_pqc::mlkem::default::keygen().unwrap();
    let (ct, ss1) = qorechain_pqc::mlkem::default::encapsulate(&ek).unwrap();
    let ss2 = qorechain_pqc::mlkem::default::decapsulate(&dk, &ct).unwrap();
    assert_eq!(ss1, ss2);
}
